--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS parvinhajili;
--
-- Name: parvinhajili; Type: DATABASE; Schema: -; Owner: parvinhajili
--

CREATE DATABASE parvinhajili WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE parvinhajili OWNER TO parvinhajili;

\connect parvinhajili

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: book_and_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_and_user (
    id integer NOT NULL,
    book_id integer NOT NULL,
    drop_off_time timestamp without time zone,
    pick_up_time timestamp without time zone,
    user_id integer NOT NULL
);


ALTER TABLE public.book_and_user OWNER TO postgres;

--
-- Name: book_and_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book_and_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_and_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books (
    id integer NOT NULL,
    author character varying(255),
    category character varying(255),
    name character varying(255),
    published_date character varying(255),
    taken_by integer NOT NULL
);


ALTER TABLE public.books OWNER TO postgres;

--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_user; Type: TABLE; Schema: public; Owner: parvinhajili
--

CREATE TABLE public.course_user (
    enroll_id integer NOT NULL,
    user_email character varying,
    course_id integer
);


ALTER TABLE public.course_user OWNER TO parvinhajili;

--
-- Name: course_user_enroll_id_seq; Type: SEQUENCE; Schema: public; Owner: parvinhajili
--

CREATE SEQUENCE public.course_user_enroll_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.course_user_enroll_id_seq OWNER TO parvinhajili;

--
-- Name: course_user_enroll_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: parvinhajili
--

ALTER SEQUENCE public.course_user_enroll_id_seq OWNED BY public.course_user.enroll_id;


--
-- Name: courses; Type: TABLE; Schema: public; Owner: parvinhajili
--

CREATE TABLE public.courses (
    course_id integer NOT NULL,
    course_name character varying
);


ALTER TABLE public.courses OWNER TO parvinhajili;

--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: parvinhajili
--

CREATE SEQUENCE public.courses_course_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.courses_course_id_seq OWNER TO parvinhajili;

--
-- Name: courses_course_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: parvinhajili
--

ALTER SEQUENCE public.courses_course_id_seq OWNED BY public.courses.course_id;


--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255),
    token integer NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: course_user enroll_id; Type: DEFAULT; Schema: public; Owner: parvinhajili
--

ALTER TABLE ONLY public.course_user ALTER COLUMN enroll_id SET DEFAULT nextval('public.course_user_enroll_id_seq'::regclass);


--
-- Name: courses course_id; Type: DEFAULT; Schema: public; Owner: parvinhajili
--

ALTER TABLE ONLY public.courses ALTER COLUMN course_id SET DEFAULT nextval('public.courses_course_id_seq'::regclass);


--
-- Data for Name: book_and_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book_and_user (id, book_id, drop_off_time, pick_up_time, user_id) FROM stdin;
\.


--
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.books (id, author, category, name, published_date, taken_by) FROM stdin;
\.


--
-- Data for Name: course_user; Type: TABLE DATA; Schema: public; Owner: parvinhajili
--

COPY public.course_user (enroll_id, user_email, course_id) FROM stdin;
1	nijat.ahmadli@tourismboard.az	1
2	nijat.ahmadli@tourismboard.az	4
\.


--
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: parvinhajili
--

COPY public.courses (course_id, course_name) FROM stdin;
1	Math
2	PHY
3	Safety
4	Test
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, firstname, lastname, password, token) FROM stdin;
\.


--
-- Name: book_and_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_and_user_id_seq', 1, false);


--
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.books_id_seq', 1, false);


--
-- Name: course_user_enroll_id_seq; Type: SEQUENCE SET; Schema: public; Owner: parvinhajili
--

SELECT pg_catalog.setval('public.course_user_enroll_id_seq', 2, true);


--
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: parvinhajili
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 1, false);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- Name: book_and_user book_and_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_and_user
    ADD CONSTRAINT book_and_user_pkey PRIMARY KEY (id);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

